/**
 * Machine-readable error codes returned in the standardised error response.
 * Keep these stable — clients may branch on them.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',

  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_INACTIVE = 'AGENT_INACTIVE',

  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_COMPLETED = 'TRANSACTION_ALREADY_COMPLETED',

  INVALID_STAGE_TRANSITION = 'INVALID_STAGE_TRANSITION',

  COMMISSION_CALCULATION_ERROR = 'COMMISSION_CALCULATION_ERROR',
  COMMISSION_BREAKDOWN_NOT_FOUND = 'COMMISSION_BREAKDOWN_NOT_FOUND',

  INVALID_REFERENCE_CODE = 'INVALID_REFERENCE_CODE',
}
